### ISSUE TITLE
Rest Support?

### ISSUE THREAD

**Issue by jelitox** [modlinltd/django-advanced-filters#10]
Hi, great proyect, It's possible get working with rest querys instead of models aproach?

**Comment by asfaltboy** [comment]
Hi @jelitox thanks for your interest in our project. Can you please add a bit more details on what you mean by "REST queries"? People use the term to mean different things.

**Comment by macagua** [comment]
Yes @jelitox please, add a bit more details about your request!

**Comment by asfaltboy** [comment]
Going to close this for now, as without details it's unclear what can be done.
