### ISSUE TITLE
Release 1.1.1

### ISSUE THREAD

**Issue by ebertti** [modlinltd/django-advanced-filters#101]
Hi,

I have problem with encode when open `CHANGELOG.rst`

This commit fix it:

https://github.com/modlinltd/django-advanced-filters/commit/b6bdb8cc634706b7d7d8a9c3817f2548a3346f1f#diff-2eeaed663bd0d25b7e608891384b7298

But this is in develop branch.

Can you release this new version 😄 

PS: Thanks for your project, great job!

**Comment by asfaltboy** [comment]
Done released, please check it out and let us know if all works well:
https://pypi.org/project/django-advanced-filters/
