### ISSUE TITLE
Is this under development?

### ISSUE THREAD

**Issue by lorenzomorandini** [modlinltd/django-advanced-filters#104]
As title, is this under development? It would be useful for our project but there are so many bug it's not worth using right now. The daterange doesn't work correctly, same for the select2.

**Comment by asfaltboy** [comment]
Hi @lorenzomorandini , I'm not aware of any immediate issues, but it's not actively under development as I don't work for modlin any longer (not sure if they're using it still).

That said, this is an open source project, and most issues are easily fixed. My only concern is to keep the current users happy. Please have a look at a similar report on date-picker in #85 maybe that will give you a clue about what is wrong, and if you come up with more information or better yet, a solution, please feel free to submit a ticket/PR.
