### ISSUE TITLE
Able to use this on non-admin page?

### ISSUE THREAD

**Issue by nabobalis** [modlinltd/django-advanced-filters#107]
I was wondering if it was possible to somehow implement the filter view as a page/menu that a normal user could access instead of being tied to the admin site?

**Comment by asfaltboy** [comment]
Sure, one can definitely use it outside of the admin, you just need to implement an (optionally paginated) [generic `ListView`][1], integrate the `AdvancedFilterForm` and use it similarly to how is done in the `AdminAdvancedFiltersMixin` and the related `AdvancedListFilters`.

If you do implement some generic view of this kind, please feel free to contribute a PR.

[1]: https://docs.djangoproject.com/en/2.2/ref/class-based-views/generic-display/#listview

**Comment by willismonroe** [comment]
I'm just wondering if you had any more advice on how to implement this for a user-facing advanced search/filter page.  This seems like the ideal way to build advanced queries of a relational db running in Django.
