### ISSUE TITLE
Upgrade to Django 3.0.2: django.utils.six problem

### ISSUE THREAD

**Issue by MHM5000** [modlinltd/django-advanced-filters#110]
**Describe the bug**
Since Django removed `django.utils.six` from its core, we should be using the `six` package.

**To Reproduce**
Install `django-advanced-filters` in a `django>=3.0.0` environment.

**Expected behavior**
Work without any problem!

**Details (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version 3.6.8
 - Django version 3.0.2
 - django-advanced-filters version 1.1.1
 - Browser -
 - Version -

**Additional context**
```sh
  File "/some/sub/folder/proj/proj/urls.py", line 40, in <module>
    path('advanced_filters/', include('advanced_filters.urls')),

```
or
```sh
  File "/some/sub/folder/proj/app/admin.py", line 9, in <module>
    from advanced_filters.admin import AdminAdvancedFiltersMixin

```

**Comment by serjant** [comment]
I am having the same issue

**Comment by asfaltboy** [comment]
Thanks guys, would either of you consider submitting a pull-request to fix this?
Also, adding Django 3.0 to the test matrix would make this support "official"

**Comment by zbynekdrlik** [comment]
+1

**Comment by zbynekdrlik** [comment]
When the new version will be out?
