### ISSUE TITLE
Maintenance of package

### ISSUE THREAD

**Issue by DmytroLitvinov** [modlinltd/django-advanced-filters#115]
Hello @asfaltboy ,

I would like to say thanks to your efforts for creating such already ready decision of advanced filtering which could be done on UI.

There is a question from my side and probably from community: what is the current situation with that library? Any activity on it? Or it is inactive and you are looking for active development team/person.

I am ready prepare MR for supporting only Django 1.11-2.2 and Python 2.7,3.5,3.6,3.7 only.
Please, let me know you opinion on that or tag someone who is responsible on it.
Looking forward to seeing your message/ping :)

**Comment by asfaltboy** [comment]
Hey @DmytroLitvinov , a few people have submitted PRs for bumping required versions already. I meant to handle them for a few months now, but unfortunately, life got in the way. I'll have a look now which ones make sense and which are mute.

**Comment by asfaltboy** [comment]
@DmytroLitvinov please try out the version in develop branch and let me know if it works well for you. If it solves the issue, we can freeze a release for this change.
