### ISSUE TITLE
Editing advanced filter says operator is always "DateTime Range"

### ISSUE THREAD

**Issue by PeterTillema** [modlinltd/django-advanced-filters#121]
**Describe the bug**
No matter what type you select, when editing an advanced filter, it says the type (or operator) is *always* a DateTime Range, even though that isn't true.

**Comment by asfaltboy** [comment]
Is this still an issue? If yes, please reopen and kindly provide step-by-step instructions and details on the versions (see [the issue template for details](https://github.com/modlinltd/django-advanced-filters/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md))
