### ISSUE TITLE
Library does not support django3

### ISSUE THREAD

**Issue by 30mb1** [modlinltd/django-advanced-filters#123]
django-braces==1.13.0 does not support django3.0, need upgrade to 1.14.0
I found several bugs with this version:
1. It points to django.utils.six, which is removed in django3.0
2. It points to curry function from django.utils.functional which is removed in django3.0

**Comment by asfaltboy** [comment]
Thanks for the report @30mb1 and it seems this is already fixed by contribution #122 .
Kindly try and see if `develop` branch fixes this for you, and report back of any issues.
Release will be done in later on
