### ISSUE TITLE
Django 3.1.5 crashes when trying to use django-advanced-filters.

### ISSUE THREAD

**Issue by caramdache** [modlinltd/django-advanced-filters#137]
**Describe the bug**
Django 3.1.5 crashes when trying to use django-advanced-filters.

**Errors generated**
 - ImportError: cannot import name 'FieldDoesNotExist' from 'django.db.models.fields'
 - ImportError: cannot import name 'six' from 'django.utils'

**Expected behavior**
Should be able to run on django 3.1.5 without any error.
It should not be necessary to install six.

**Details (please complete the following information):**
 - django-advanced-filters version 1.2.0
 - Django version 3.1.5
 - Python version 3.9.1

**Comment by asfaltboy** [comment]
Sorry, we've got a fix in Develop, forgot to release new ver. Working on it
