### ISSUE TITLE
Cannot pick a field to filter

### ISSUE THREAD

**Issue by dgleba** [modlinltd/django-advanced-filters#14]
Thank you for your efforts on this feature!

## My Issue:
I see the filter form, but it says the following in the field dropdown.

"Or (mark an or between blocks)"

Screen shot attached.

Can someone help me understand what I am doing wrong?

thanks,

### My Installation.

I installed django edge.
Then installed modlinltd/django-advanced-filters

### Info:

Django 1.8.11
Windows.

### My code in admin.py:

> from advanced_filters.admin import AdvancedFilterAdmin, AdminAdvancedFiltersMixin
>   
> class Cilisting1Admin( AdminAdvancedFiltersMixin, admin.ModelAdmin ):
> 
>  .....  some other stuff ....
>
> list_filter = (
>     'wc_idea_date',
>     'actual_implementation_date',
>     )
> 
> advanced_filter_fields = (
>     'owner',  'originator',  'project_number',
>     )

___________

### My installation steps. (Possibly unneeded detail)

http://django-edge.readthedocs.org/en/latest/#quick-start
 
 django-admin.py startproject --template= \
       https://github.com/arocks/edge/archive/master.zip -extension=py,md,html,env    my_proj
 cd my_proj
 pip install -r requirements.txt 
 cd src
 cp my_proj/settings/local.sample.env my_proj/settings/local.env
 python manage.py migrate
 python manage.py createsuperuser
 python manage.py runserver 0.0.0.0:8000

 python manage.py startapp cilist1
 edit cilist1 models.py
 edit base.py - add clist1 app
 python manage.py makemigrations cilist1
 python manage.py sqlmigrate cilist1 0001
 python manage.py makemigrations 
 python manage.py migrate
 edit cilist1 admin.py
 python manage.py runserver 0.0.0.0:8000

 An aside... I moved to Windows...
 set wpip=c:\p2\Python27\Scripts\pip
 %wpip% install -r requirements.txt
 cd src
 python manage.py runserver 0.0.0.0:8000

 %wpip% install django-advanced-filters

 Install from pypi: pip install django-advanced-filters
 Add both 'advanced_filters' and 'easy_select2' to INSTALLED_APPS.
 Add url(r'^advanced_filters/', include('advanced_filters.urls')) to your project's urlconf.
 Run python manage.py syncdb

 %wpip% install django-grappelli
 added grapelli to installed apps.

=====
______
______

![issue--fields not showing in advanced filter modlinltd](https://cloud.githubusercontent.com/assets/4622715/13858107/7d8a16ba-ec53-11e5-8a3f-3a76208c72ad.png)

**Comment by asfaltboy** [comment]
Hi @dgleba thank you for your interest. Can you share your `ModelAdmin` definition? Take not that the field definition is not implicit; you have to explicitly list each field you want to be able to filter by in the `advanced_filter_fields ` property, as [demonstrated in the README][1].

[1]: https://github.com/modlinltd/django-advanced-filters#integration-example

**Comment by dgleba** [comment]
Sorry, I was editing that into my comment as you answered. 

It is there now. 

Thanks for the quick response.

**Comment by asfaltboy** [comment]
So your fields list is empty? Can you check your browser javascript console for any errors? Also, you don't need grappelli anymore, and both should be supported, but just for a check try removing grappelli.

**Comment by dgleba** [comment]
The fields list in the advanced filter form is empty.

Screen shots attached of javascript console with and without grappelli. It's empty either way.

==

full code for my test app is here:

https://github.com/dgleba/edge225b

==

![without grapelli](https://cloud.githubusercontent.com/assets/4622715/13859445/d64ad9e6-ec59-11e5-9c9c-d22fc6bf7cfd.png)
==

![with grapelli](https://cloud.githubusercontent.com/assets/4622715/13859444/d64a5b10-ec59-11e5-9958-ffacc352d69f.png)

**Comment by dgleba** [comment]
I  installed  `django-advanced-filters` from github.
It still has the problem.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Title:  I tried to install from github..
-----------------------2016-03-17[Mar-Thu]16-18PM


set wpip=c:\p2\Python27\Scripts\pip

%wpip% install https://github.com/modlinltd/django-advanced-filters/tarball/master

_____________



C:\n\web\edge225b\my_proj\src>set wpip=c:\p2\Python27\Scripts\pip

C:\n\web\edge225b\my_proj\src>
C:\n\web\edge225b\my_proj\src>%wpip% install https://github.com/modlinltd/django-advanced-filters/tarball/master
Downloading/unpacking https://github.com/modlinltd/django-advanced-filters/tarball/master
  Running setup.py (path:c:\users\dgleba\appdata\local\temp\pip-ieqn9p-build\setup.py) egg_info for package from https://g
ithub.com/modlinltd/django-advanced-filters/tarball/master
    PyPandoc not installed. Cannot convert README.md to rst

  Requirement already satisfied (use --upgrade to upgrade): django-advanced-filters==1.0.1 from https://github.com/modlinl
td/django-advanced-filters/tarball/master in c:\p2\python27\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): django-easy-select2==1.2.5 in c:\p2\python27\lib\site-packages (
from django-advanced-filters==1.0.1)
Downloading/unpacking django-braces==1.4.0 (from django-advanced-filters==1.0.1)
  Downloading django_braces-1.4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): simplejson==3.6.5 in c:\p2\python27\lib\site-packages (from djan
go-advanced-filters==1.0.1)
Requirement already satisfied (use --upgrade to upgrade): six in c:\p2\python27\lib\site-packages (from django-braces==1.4
.0->django-advanced-filters==1.0.1)
Installing collected packages: django-braces
  Found existing installation: django-braces 1.8.1
    Uninstalling django-braces:
      Successfully uninstalled django-braces
Successfully installed django-braces
Cleaning up...
C:\n\web\edge225b\my_proj\src>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by asfaltboy** [comment]
Firstly, the javascript errors are odd, we don't use `grappelli` (i.e the `grp` object) in no javascript files in latest released version 1.0.1 (master), did you upgrade from a previous version?

Second, it is unfortunate that the form looks bad with `django-edge`, but I cannot expect all themes to display the form nicely, and this may require some work. If you find a nice set of CSS rules that work, I'd appreciate a pull request.

Finally, GitHub `master` branch should equal the latest release on PyPI, so I still cannot see why your field list would be empty. Tell me, are the listed fields (`'owner', 'originator', 'project_number'`) actual fields on your `Model`, or are they inherited, methods or other?

In any case, my apologies for the slow replies, I'll have a closer look at this in the weekend, before I release the 1.0.2 version.

**Comment by dgleba** [comment]
I did not upgrade from a previous version. I just installed it initially yesterday.

The fields ('owner', 'originator', 'project_number') are directly part of the  model.
The model can be seen here..  https://github.com/dgleba/edge225b/blob/master/my_proj/src/cilist1/models.py

I will try this in a clean ubuntu vm with virtualenv and see what results I get there.

Thank you for looking at this.

**Comment by asfaltboy** [comment]
The issue seems to be with the indentation in your `admin.py` module. The tuples `list_display`, `list_display_links`, `advanced_filter_fields` and `list_per_page` must all be properties of `Cilisting1Admin` but [are currently not - they are under-indented](https://github.com/dgleba/edge225b/blob/master/my_proj/src/cilist1/admin.py#L100)!

The solution is to add 4 spaces to all of the above to make them properties of the `ModelAdmin`. Here's a screenshot of what happens after you fix that (see PR dgleba/edge225b#1 to your project for the code):

<img width="701" alt="screen shot 2016-03-20 at 9 07 01 am" src="https://cloud.githubusercontent.com/assets/321520/13903463/b0cd2898-ee7c-11e5-8c81-9f236809b9cb.png">

**Comment by dgleba** [comment]
I am very sorry I put you through this. I am embarrassed. That was not your issue at all. 

Thank you for looking at this. It was stupid on my part.

All is, of course, working well after indenting properly.

Again I am sorry for wasting your time.

**Comment by asfaltboy** [comment]
Don't worry mate :) it's no trouble at all, good to hear your issue is resolved!

**Comment by dgleba** [comment]
Thanks.
