### ISSUE TITLE
Modal does not respect dark mode

### ISSUE THREAD

**Issue by VaZark** [modlinltd/django-advanced-filters#172]
**Describe the bug**
When the search modal is opened in a browser that has dark mode by default. The theming support was added in django 3.2 ([link](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/#admin-theming))

**To Reproduce**
1. Set browser to prefer dark mode
2. Open the advanced filter modal on any page

**Expected behavior**
The modal should respect the CSS variables from django 3.2

**Screenshots**
![image](https://user-images.githubusercontent.com/11616688/187199126-c31f239d-f38b-4e27-b7de-83bf6c59ff55.png)

**Details (please complete the following information):**
 - OS: linux
 - Python version : 3.9
 - Django version : 4.0
 - django-advanced-filters version  : 2.0.0
 - Browser : Firefox
 - Version : 10

**Comment by VaZark** [comment]
CSS variables are available at : https://github.com/django/django/blob/main/django/contrib/admin/static/admin/css/base.css

**Comment by asfaltboy** [comment]
Thanks @VaZark , I switched to the `var(--body-bg)` in PR #176 . Could you give a try and let me know if it resolves your concern? My hope is it's a tiny bit simpler than the changes proposed in PR #173

**Comment by VaZark** [comment]
Looks like the there one little field that has not been updated

![image](https://user-images.githubusercontent.com/11616688/194908328-b50c678a-4b9f-4174-866c-5aaec72c4f5d.png)

**Comment by asfaltboy** [comment]
Thanks for reminding me about it 🙇

Django has an autocomplete.css select2 theme ([see here](https://github.com/django/django/blob/f0c06f8ab7904e1fd082f2de57337f6c7e05f177/django/contrib/admin/static/admin/css/autocomplete.css#L38)) that seems to do the job. We can play around with select2 themes in the draft PR #177 , as it switched to django vendored select2 v4.
