### ISSUE TITLE
Add custom list filter to advanced_filter_fields list

### ISSUE THREAD

**Issue by hermanocabral** [modlinltd/django-advanced-filters#29]
Howdy,

How would I go about having a custom filter in the advanced_filter_fields list?

I have a scenario where I have a Person model with gender defined as a boolean field, but I'd like to give admin users the option to filter by "Male"/"Female" instead of by True/False.

I can use something like the GenderListFilter below in the admin page, but how do I go about doing something similar with advanced filters?

Thanks.

```
class Person(models.Model):
    is_male = models.BooleanField(verbose_name='Is Male', blank=False, null=False, default=False)


class GenderListFilter(admin.SimpleListFilter):
    title = 'Gender'
    parameter_name = 'gender'

    def lookups(self, request, model_admin):
        return (
            ('M', 'Male'),
            ('F', 'Female')
        )

    def queryset(self, request, queryset):
        if not self.value():
            return queryset

        if self.value().lower() == 'm':
            return queryset.filter(is_male=True)
        else:
            return queryset.filter(is_male=False)
```

**Comment by asfaltboy** [comment]
Hi @hermanocabral,

We don't support something like operator customization per field right now.

You could, if that was the only boolean field you wanted to filter on for this ModelAdmin, subclass the [`AdvancedFilterQueryForm` form][1] and specify your own label:

```python
class CustomLabelAdvancedFilterQueryForm(AdvancedFilterQueryForm):
    """ Build the query from field, operator and value, customizing the boolean values """
    OPERATORS = AdvancedFilterQueryForm.OPERATORS + (
        ("istrue", _("Is Male")),
        ("isfalse", _("Is Female")),
    )
```

Replacing the above form means you'd also have to construct your own formset, and use it in `AdvancedFilterForm. initialize_form `

Though to be clear, I would probably make a field such as gender selection, an int/char field with 2 choices, which would be properly rendered by our form.

[1]: https://github.com/modlinltd/django-advanced-filters/blob/develop/advanced_filters/forms.py#L46

**Comment by asfaltboy** [comment]
@hermanocabral I've gone ahead and closed the issue, please reopen if you need further help.
