### ISSUE TITLE
should use latest updated Requirements ex. django-easy-select2==1.3.3

### ISSUE THREAD

**Issue by sanchig** [modlinltd/django-advanced-filters#33]
we are using latest django-easy-select2 and simplejson for our project requirement. but when we are try to install django-advanced-filters this will start to auto download old versions of Requirements. I think you should use latest version of all Requirements.
We are using this command to install (for ref.)
pip install django-advanced-filters

**Comment by asfaltboy** [comment]
Hi @sanchig , thank you for your bug report!

In general I'm all in favor of using newest versions of dependencies; however, we need to make sure these newer versions don't break current functionality. Our current requirenetns are:

```python
'django-easy-select2==1.2.5',
'django-braces==1.4.0',
'simplejson>=3.6.5',
```

Simplejson [doesn't seem to be breaking anything][1], so we could bump and soft freeze >=3.8.2. And django-braces also [seems fine][2].

As for `django-easy-select2`, [version 1.3 removes deprecated `Select2TextInput`][3] which is imported in [advanced_filters/form_helpers.py][4]. We need to have a look how to replace it.

As always, PR is appreceiated.

[1]: https://github.com/simplejson/simplejson/blob/master/CHANGES.txt
[2]: https://django-braces.readthedocs.io/en/latest/changelog.html
[3]: https://github.com/asyncee/django-easy-select2/blob/master/docs/source/changelog.rst#version-13
[4]: https://github.com/modlinltd/django-advanced-filters/blob/master/advanced_filters/form_helpers.py

**Comment by asfaltboy** [comment]
As reported in issue #34, upgrading (or replacing) `django-easy-select` is a requirement to add support for Django 1.10.

**Comment by asfaltboy** [comment]
Ha, silly me! I grepped the code and we don't even use any functionality of `django-easy-select2`! This basically means that we can include the js/css manually and remove this dependency entirely!

**Comment by asfaltboy** [comment]
PR #36 makes this a non-issue, 1.0.5 will be release shortly
