### ISSUE TITLE
Django 1.10 Unable to Save Filter

### ISSUE THREAD

**Issue by gbot300** [modlinltd/django-advanced-filters#48]
Great lib!

I'm running Django 1.10 with Python3.5.

From my admin interface, I'm able to see the ADVANCED FILTER button. I can click it and it opens the interface, where I can enter a title, select fields etc. However, I cannot SAVE / SAVE & FILTER NOW! or "Add another Field". The only link that works is Cancel...

I've added 'easy_select2' to my installed_apps (something which isn't mentioned on this GitHub page, but is on the pypi page.

**Comment by asfaltboy** [comment]
Hi @gbot300 ! Thank you for the issue.

I think you're experiencing the same issue mentioned in PR #42 . Can you try installing the package from develop branch to see if it resolves your issue?

**Comment by gbot300** [comment]
Hi @asfaltboy 

Right - I installed the "develop" branch using pip3

I run into this error now: 

![screenshot from 2017-04-28 17-38-43](https://cloud.githubusercontent.com/assets/6552456/25536084/b3a5f24c-2c39-11e7-842b-18bc805644e0.png)

**Comment by gbot300** [comment]
Changing the first line in the advanced_filters.html template to 
{% extends "admin/change_list.html" %}
solves the issue

The "Add Filter" pop-up now works, I can "save" and "save&filter". The "Add another filter" link doesn't work though. If, however, I edit filters from the Admin home once they have been created, I am able to add additional filters.

Thanks again for the great lib! I'll keep an eye on the development to see if these issues are resolved, but I can go on with what I have now.

cheers

**Comment by asfaltboy** [comment]
That is odd. In your admin class, that mixes in `AdminAdvancedFiltersMixin`, do you override `change_list_template` by any chance?

**Comment by gbot300** [comment]
OK - I for got to migrate after installing the new branch. The change_list_template is no longer an issue.
Adding additional filters from the pop-up also works now.

Now I'm getting TypeErrors (Related Field got invalid lookup: iexact) (also icontains) on foreign key filters. When adding Boolean filters, I get an error that the Value field must be filled in.

Haha, sorry man. I am not a great Django wizard - I represent the low end of the user base!

**Comment by gbot300** [comment]
This seems to be my own issue with the way I list the foreign key relationships in the "advanced_filter_fields" in my Admin class.

**Comment by asfaltboy** [comment]
No worries dude/dudette, you're the perfect test candidate!

**Comment by mgrdcm** [comment]
I'm having this issue as well (1.10/2.7 in Safari).  Anything I can do to help out with this?

**Comment by asfaltboy** [comment]
@mgrdcm since #42 was merged, you could just install the develop branch from github instead of pypi. E.g

    pip install https://github.com/modlinltd/django-advanced-filters.git@develop

Let us know how the develop branch is working for you, it will be soon time for next release.

**Comment by asfaltboy** [comment]
I'm going to close this issue, if this issue is not resolved in develop or other issues pop up, feel free to reopen 😊
