### ISSUE TITLE
select2 undefined on query-value

### ISSUE THREAD

**Issue by agix** [modlinltd/django-advanced-filters#5]
Javascript crash on https://github.com/modlinltd/django-advanced-filters/blob/master/advanced_filters/static/advanced-filters/advanced-filters.js#L140

removing this line fix the issue as query-value is not a select form and select2 seems to work only on select form.

I have no idea if it's intended

**Comment by asfaltboy** [comment]
I believe this is intended, can't really recall what for, probably cleanup.
I do believe `select2` replaces the `select` field into a bunch of elements (and `input` is one of them), and they all have the "select2" object attached to them. In other words, this works for me.

Does `select2` works well for you everywhere else, such as in [`initialize_select2`](https://github.com/modlinltd/django-advanced-filters/blob/master/advanced_filters/static/advanced-filters/advanced-filters.js#L66)? The same call to destroy is made here too, as well as the init.

Please add some details on your scenario, step by step actions, etc.

**Comment by agix** [comment]
It crashes on initialize_select2 too.

Step by step 
I clone the repo, setup.py install it, migrate, add the settings, add the static files, and add AdminAdvancedFiltersMixin to my admin class.

I think the query-value may be transformed somewhere in a select list of choices but I don't find where or how.

**Comment by asfaltboy** [comment]
Thanks for the report, I'll attempt to reproduce and get back to you.

**Comment by eriktelepovsky** [comment]
Issue still exists in current version 1.3.0.

Django==3.1.12
Python 3.9.8

**Comment by asfaltboy** [comment]
5 years later the above issue was resolved, I can't help but wonder if this is possibly a different issue 🤔 

@eriktelepovsky kindly file a separate bug ticket with the details above as well as a traceback; from python logs, or javascript browser console, and any other information you feel relevant  🙏
