### ISSUE TITLE
jquery django 1.11

### ISSUE THREAD

**Issue by Smosker** [modlinltd/django-advanced-filters#53]
Hello! I'm using this module with django 1.11.
It works fine but 

> This means that to use advanced-filters in Django 1.5 admin, you'd have to probably include your own jQuery (1.9 or later) and add it to global namespace prior to other scripts in AdvancedFilterForm.Meta.

Can you please specify how should i do it?

**Comment by daonb** [comment]
Don't worry about it - It's for users of the ancient Django 1.5.

**Comment by asfaltboy** [comment]
@Smosker do you mean you want to use DAF in a project running Django version 1.5?
