### ISSUE TITLE
incompatibility with python 3

### ISSUE THREAD

**Issue by bjornpoort** [modlinltd/django-advanced-filters#6]
using latest stable django (1.8.7) and python 3.5 - not compatible at this moment? when applying any filter it returns this error: 

name 'basestring' is not defined
exception location: env/lib/python3.5/site-packages/advanced_filters/form_helpers.py in clean, line 29

a fix could by as mentioned here http://www.rfk.id.au/blog/entry/preparing-pyenchant-for-python-3/
"These are both errors in Python 3 since there's no such thing as 'unicode' or 'basestring'. But it's pretty simple to normalise the vocabulary between the two versions:

try:
unicode = unicode
except NameError:
# 'unicode' is undefined, must be Python 3
str = str
unicode = str
bytes = bytes
basestring = (str,bytes)
else:
# 'unicode' exists, must be Python 2
str = str
unicode = unicode
bytes = str
basestring = basestring "

Not sure how to implement this (rookie python level). Someone got an idea?

**Comment by asfaltboy** [comment]
The latest release 1.0.1 (now also [available on pypi](https://pypi.python.org/pypi/django-advanced-filters/1.0.1)) should resolve the issue. Please test and let us know.

**Comment by bjornpoort** [comment]
Works now! Very nice asfaltboy. Above issue is solved. Been testing, couple of issues came into play. You appreciate if they are raised seperately? If not, see below:

#1 There is a template error when clicking on 'advanced filter l edit' after applying:

![image](https://cloud.githubusercontent.com/assets/14273799/11716269/db6fb4e0-9f48-11e5-8f78-019a70843443.png)

#2 When Isnull operator is selected, it still requires a value.

![image](https://cloud.githubusercontent.com/assets/14273799/11716431/280d99ba-9f4a-11e5-9da2-b3c6c9d7a716.png)

#3 When m2m is filtered, raises the following error:

![image](https://cloud.githubusercontent.com/assets/14273799/11716526/b7a8ed40-9f4a-11e5-9b94-4578dad9af51.png)

**Comment by asfaltboy** [comment]
Thanks @bjornpoort! Please open issue/s; can be a single issue, but would help if you include detailed case for the M2M exception.
