### ISSUE TITLE
Option to execute filter without saving/titling it?

### ISSUE THREAD

**Issue by djpretzel** [modlinltd/django-advanced-filters#81]
Would it be possible to implement this package such that an advanced filter could be executed without the need to title or save it? The screenshot indicates saving is mandatory - if it were optional, the ability to run ad-hoc filters and save only after reviewing results would be preferable...

**Comment by asfaltboy** [comment]
Good point, I like that idea a lot, we could have a preview button, perhaps utilizing the session store (?) to preserve the form details so that we can later save after the results are displayed?

Contributions are welcome - we ❤️ PRs!

**Comment by asfaltboy** [comment]
duplicates #67
