### ISSUE TITLE
Not installing from PyPi

### ISSUE THREAD

**Issue by wilburb** [modlinltd/django-advanced-filters#9]
When I attempt to install from PyPi I receive the following. I have verified on two separate systems and do not believe it to be something on my end. Should there be something after "versions:" on the third line below? Thanks.

    $ pip install django-advanced-filters
    Collecting django-advanced-filters
      Could not find a version that satisfies the requirement django-advanced-filters (from versions: )
    No matching distribution found for django-advanced-filters

**Comment by asfaltboy** [comment]
The distribution file was weirdly missing, probably my fault, can't recall; anyway, I uploaded it now. @wilburb Please try again and let me know.
